### ISSUE TITLE
Add image pull command

### ISSUE THREAD

**Issue by nirvdrum** [simplygenius/atmos#8]
Atmos has a command for pushing up images to ECR, which is great for container-based deployments. It would be very helpful for debugging if there were a corresponding image pull command. In a continuous deployment environment it often isn't possible or very impractical to get the source image that was pushed up. Being able to pull directly from the registry would be a straightforward way to see what was actually deployed and do any debugging or inspection of the image.

Ideally, the image would be pullable by tag name so a caller could just request _latest_ or whatever the tag is for a given repository without having to get the entire image name manually from the ECR console.

**Comment by wr0ngway** [comment]
Added in 22518f3 - defaults to pulling latest, but you can also supply a revision
